apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginx.fullname" . }}-config
  labels:
    {{- include "nginx.labels" . | nindent 4 }}
data:
  upstream.conf: |-
    upstream app {
      {{- range $.Values.upstreamConfig }}
      server {{.}};
      {{- end }}
    }

    server {
      location / {
        proxy_pass http://app;
      }
    }
